# Generated by Django 4.2.10 on 2024-03-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('distance_value', models.FloatField()),
                ('vehicle_make', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_year', models.PositiveIntegerField()),
                ('vehicle_model_id', models.UUIDField()),
                ('distance_unit', models.CharField(max_length=10)),
                ('estimated_at', models.DateTimeField()),
                ('carbon_g', models.PositiveIntegerField()),
                ('carbon_lb', models.FloatField()),
                ('carbon_kg', models.FloatField()),
                ('carbon_mt', models.FloatField()),
            ],
        ),
    ]
