# Generated by Django 4.2.10 on 2024-03-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0002_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICallCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
