# Generated by Django 4.2.10 on 2024-03-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0003_apicallcounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toyotamodels',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
