# Generated by Django 4.2.10 on 2024-03-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0004_alter_toyotamodels_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='type',
        ),
        migrations.AlterField(
            model_name='estimate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='vehicle_model_id',
            field=models.CharField(max_length=100),
        ),
    ]
