# Generated by Django 4.2.10 on 2024-03-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0005_remove_estimate_type_alter_estimate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='type',
            field=models.CharField(default='estimate', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estimate',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
